[package]
name = "litt-input"
version = "0.1.0"
edition = "2021"
description = "Input system for Litt Engine — keyboard, mouse, gamepad"

[dependencies]
litt-math = { path = "../math" }
bytemuck = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_Graphics", "Win32_UI_Input_KeyboardAndMouse"] }

[target.'cfg(target_os = "linux")'.dependencies]
nix = { version = "0.29", default-features = false, features = ["fs", "input"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
