[package]
name = "litt-dx12"
version = "0.1.0"
edition = "2021"
description = "DirectX 12 backend for Litt Engine"

[lib]
path = "src/lib.rs"

[dependencies]
bytemuck = { workspace = true }
log = { workspace = true }
litt-math = { path = "../math" }
litt-platform = { path = "../platform" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
