[build]
target = "x86_64-pc-windows-gnu"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-ar"

[env]
VULKAN_SDK = { value = "C:\\Users\\roika\\AppData\\Local\\Temp\\VulkanSDK", force = true }
GLSLANG_PATH = { value = "D:\\Allgemein\\tools\\glslang\\bin\\glslang.exe", force = true }
