// Dither3D - Surface-Stable Fractal Dithering for Litt Engine
// Ported from Dither3DInclude.cginc (MPL v2.0, Rune Skovbo Johansen)
//
// C++ API for managing dither textures and material parameters.
// The GLSL shader logic is in shaders/dither3d/include.glsl.

#pragma once
#include "litt_math.h"
#include <string>
#include <vector>
#include <memory>
#include <unordered_map>

namespace litt {

// =============================================================================
// Dither Color Mode
// =============================================================================

enum class DitherColorMode : uint32_t {
    Grayscale = 0,  // Single luminance channel
    RGB         = 1,  // Per-channel dithering
    CMYK        = 2,  // Print-style halftone (15/75/0/45 degree angles)
};

// =============================================================================
// Dither Pattern Size
// =============================================================================

enum class DitherPattern : uint32_t {
    P1x1 = 0,  // 16x16x1 texture, 1 layer
    P2x2 = 1,  // 32x32x4 texture, 4 layers
    P4x4 = 2,  // 64x64x16 texture, 16 layers
    P8x8 = 3,  // 128x128x64 texture, 64 layers (recommended)
};

// =============================================================================
// Dither Material Properties
// =============================================================================

struct DitherMaterial {
    // Enable/disable dithering
    bool enabled = false;

    // Color mode
    DitherColorMode color_mode = DitherColorMode::Grayscale;

    // Pattern selection
    DitherPattern pattern = DitherPattern::P8x8;

    // Dot scale (exponential, range 2-10, default 5)
    float scale = 5.0f;

    // Size variability: 0=Bayer-style (dot count varies), 1=Halftone-style (dot size varies)
    float size_variability = 0.0f;

    // Dot contrast (range 0-2, default 1)
    float contrast = 1.0f;

    // Stretch smoothness (range 0-2, default 1)
    float stretch_smoothness = 1.0f;

    // Input brightness adjustments
    float input_exposure = 1.0f;
    float input_offset = 0.0f;

    // Debug / advanced flags
    bool inverse_dots = false;
    bool radial_compensation = false;
    bool quantize_layers = false;
    bool debug_fractal = false;

    // GPU uniform buffer layout (matches Constants struct in mesh.frag.glsl)
    // Layout: packed float32, 8x4 = 32 bytes
    struct Uniforms {
        // Original material constants (first 4 floats from material)
        float albedo_r = 1.0f;
        float albedo_g = 1.0f;
        float albedo_b = 1.0f;
        float metallic = 0.0f;

        // Dither parameters
        float dither_enabled = 0.0f;
        float dither_scale = 5.0f;
        float dither_size_var = 0.0f;
        float dither_contrast = 1.0f;

        // Extra uniforms
        uint32_t dither_color_mode = 0;
        uint32_t dither_pattern = 3;
        float dither_input_exp = 1.0f;
        float dither_input_off = 0.0f;
    };

    Uniforms to_uniforms() const {
        Uniforms u{};
        u.dither_enabled = enabled ? 1.0f : 0.0f;
        u.dither_scale = scale;
        u.dither_size_var = size_variability;
        u.dither_contrast = contrast;
        u.dither_color_mode = static_cast<uint32_t>(color_mode);
        u.dither_pattern = static_cast<uint32_t>(pattern);
        u.dither_input_exp = input_exposure;
        u.dither_input_off = input_offset;
        return u;
    }
};

// =============================================================================
// Dither Texture Asset
// =============================================================================

struct DitherTexture {
    std::string name;
    DitherPattern pattern = DitherPattern::P8x8;

    // 3D texture data: [width][height][depth]
    // For P8x8: 128x128x64 = 1,048,576 texels (GL_R8 format)
    std::vector<uint8_t> data;
    uint32_t width = 128;
    uint32_t height = 128;
    uint32_t depth = 64;

    // GPU handle (backend-specific)
    void* gpu_handle = nullptr;
};

struct DitherRampTexture {
    std::string name;
    std::vector<uint8_t> data;
    uint32_t width = 256;
    uint32_t height = 1;
    void* gpu_handle = nullptr;
};

// =============================================================================
// Dither Asset Manager
// =============================================================================

class DitherAssetManager {
public:
    DitherAssetManager() = default;
    ~DitherAssetManager() = default;

    // Load dither 3D texture from PNG source file
    // PNGs are generated by the Dither3D Unity package or can be created via build script
    bool load_3d_texture(const std::string& path, DitherTexture* out);

    // Load ramp texture (1D lookup table for brightness curve)
    bool load_ramp_texture(const std::string& path, DitherRampTexture* out);

    // Get built-in texture by pattern type
    const DitherTexture& get_texture(DitherPattern pattern) const;
    const DitherRampTexture& get_ramp() const;

    // Generate dither 3D textures from scratch (for engines without Unity)
    // Creates the fractal dither patterns programmatically
    void generate_textures();

    // Compile-time texture size lookup
    static uint32_t get_texture_width(DitherPattern p);
    static uint32_t get_texture_depth(DitherPattern p);
    static uint32_t get_dots_per_side(DitherPattern p);

private:
    std::unordered_map<DitherPattern, DitherTexture> textures_;
    DitherRampTexture ramp_;
    bool textures_generated_ = false;
};

// =============================================================================
// Inline Implementations
// =============================================================================

inline uint32_t DitherAssetManager::get_texture_width(DitherPattern p) {
    switch (p) {
        case DitherPattern::P1x1: return 16;
        case DitherPattern::P2x2: return 32;
        case DitherPattern::P4x4: return 64;
        case DitherPattern::P8x8: return 128;
    }
    return 128;
}

inline uint32_t DitherAssetManager::get_texture_depth(DitherPattern p) {
    switch (p) {
        case DitherPattern::P1x1: return 1;
        case DitherPattern::P2x2: return 4;
        case DitherPattern::P4x4: return 16;
        case DitherPattern::P8x8: return 64;
    }
    return 64;
}

inline uint32_t DitherAssetManager::get_dots_per_side(DitherPattern p) {
    // dotsPerSide = textureWidth / 16 (from shader constant)
    return get_texture_width(p) / 16;
}

inline const DitherTexture& DitherAssetManager::get_texture(DitherPattern p) const {
    auto it = textures_.find(p);
    if (it != textures_.end()) return it->second;
    // Fallback to 8x8
    auto fallback = textures_.find(DitherPattern::P8x8);
    return fallback != textures_.end() ? fallback->second : textures_.at(DitherPattern::P8x8);
}

inline const DitherRampTexture& DitherAssetManager::get_ramp() const {
    return ramp_;
}

} // namespace litt
