[package]
name = "litt-math"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
bytemuck = { version = "1", features = ["derive", "extern_crate_alloc"] }

[features]
default = ["std"]
std = []

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
