[package]
name = "litt-profiler"
version = "0.1.0"
edition = "2021"
description = "Profiler for Litt Engine -- performance monitoring and debugging"

[dependencies]
ash = { workspace = true }
litt-math = { path = "../math" }
bytemuck = { workspace = true }
log = { workspace = true }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

